---
title: "{{< animate flipInX 'Site Patch Notes' >}}"
subtitle: "{{< animate flipInX 'Patches upon patches upon patches...' >}}"
description: "[Does that end up being the [Ship of Thesius](https://en.wikipedia.org/wiki/Ship_of_Theseus)?]{.animate__animated .animate__flipInX style='display:inline-block;'}"
comments: false
open-graph:
  description: Patches upon patches upon patches...
twitter-card:
  description: Patches upon patches upon patches...
---

:::{.callout-note appearance="simple"}
Detailed patchnotes are unavailable prior to site version 2.0.0.0.
:::

## Version 2.2.1.2 | 3 August 2023 {.animate__animated .animate__slideInRight .animate__faster}

* Removed featured posts section in the ForBlog.

## Version 2.2.1.1 | 1 August 2023 {.animate__animated .animate__slideInLeft .animate__faster}

* Split website footer into 3 sections.

## Version 2.2.1.0 | 31 July 2023 {.animate__animated .animate__slideInRight .animate__faster}

* Added a featured posts section in the ForBlog.
* Increased thumbnail size in the App Playground.
* Fixed Ship of Theseus link in patch notes.

## Version 2.2.0.2 | 15 July 2023 {.animate__animated .animate__slideInLeft .animate__faster}

* Re-enabled App Playground.

## Version 2.2.0.1 | 13 May 2023 {.animate__animated .animate__slideInRight .animate__faster}

* Fixed animations for the App Playground.
* Fixed back-to-top button covering content on the About Me page.

## Version 2.2.0.0 | 13 May 2023 {.animate__animated .animate__slideInLeft .animate__faster}

* Implemented site-wide animations!
* Consolidated unsubscribe form and all subscribe forms into a single form.
* Added a back-to-top button.
* RSS and source code navbar icons are now positioned more cleanly when accessed from the drop down menu on smaller screens.
* Increased number of displayed posts on the ForBlog from 5 per page to 7 per page.
* Changed Home navbar icon.
* Temporarily disabled App Playground.

## Version 2.1.0.1 | 25 March 2023 {.animate__animated .animate__slideInRight .animate__faster}

* Tweaked the various subscription forms' positioning.

## Version 2.1.0.0 | 23 February 2023 {.animate__animated .animate__slideInLeft .animate__faster}

* Launched the AI dictionary.
* Shortened navbar text.

## Version 2.0.3.2 | 22 February 2023 {.animate__animated .animate__slideInRight .animate__faster}

* Updated copyright notices for 2023.

## Version 2.0.3.1 | 28 January 2023 {.animate__animated .animate__slideInLeft .animate__faster}

* Changed comment section theme.

## Version 2.0.3.0 | 27 November 2022 {.animate__animated .animate__slideInRight .animate__faster}

* Fully implemented Twitter Cards.

## Version 2.0.2.0 | 26 November 2022 {.animate__animated .animate__slideInLeft .animate__faster}

* Fully implemented Open Graph.
* Added button for direct link to site's source code.
* Tweaked landing page description.

## Version 2.0.1.2 | 17 November 2022 {.animate__animated .animate__slideInRight .animate__faster}

* Fixed broken license link.

## Version 2.0.1.1 | 17 November 2022 {.animate__animated .animate__slideInLeft .animate__faster}

* Fixed broken site feedback link.
* Updated site version references.

## Version 2.0.1.0 | 17 November 2022 {.animate__animated .animate__slideInRight .animate__faster}

* Fixed a bunch of broken links.
* Fixed RSS buttons.
* Shifted links on the landing page.

## Version 2.0.0.0 | 16 November 2022 {.animate__animated .animate__slideInRight .animate__faster}

* Created, erm, site patch notes.
* Site is now entirely remade in [Quarto](https://quarto.org).
* UI overhaul.
* ForBlog is no longer the main landing page.
* App playground has been added; a place where I can host my various creations.

New...

* favicon.
* about me page.
* landing page.
* ForBlog home page.
* ForBlog post layout.
* global search bar.

Added...

* a ForBlog only search bar.
* ForBlog post filters.
* ForBlog and App Playground subscriptions.
* a form for site feedback.
* copyright licences.
* new fancy buttons.

## Version 1.0.0.0 | 15 May 2022 {.animate__animated .animate__slideInLeft .animate__faster}

* Initial release.
* Site is built on [fastpages](https://github.com/fastai/fastpages), by [fastai](https://fast.ai).
